version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: sprout-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sprout
      POSTGRES_PASSWORD: sprout
      POSTGRES_DB: sprout
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
